src/Entity/Entreprise.php
<?php

namespace App\Entity;

use App\Repository\EntrepriseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EntrepriseRepository::class)]
class Entreprise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 100)]
    private ?string $raisonSociale = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateCreation = null;

    #[ORM\Column(length: 100)]
    private ?string $adresse = null;

    #[ORM\Column(length: 20)]
    private ?string $codePostal = null;

    #[ORM\Column(length: 50)]
    private ?string $ville = null;

    /**
     * @var Collection<int, Employe>
     */
    #[ORM\OneToMany(targetEntity: Employe::class, mappedBy: 'entreprise', orphanRemoval: true)]
    #[ORM\OrderBy(["nom" => "ASC"])]
    private Collection $employes;

    public function __construct()
    {
        $this->employes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getRaisonSociale(): ?string
    {
        return $this->raisonSociale;
    }

    public function setRaisonSociale(string $raisonSociale): static
    {
        $this->raisonSociale = $raisonSociale;

        return $this;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->dateCreation;
    }

    public function setDateCreation(\DateTimeInterface $dateCreation): static
    {
        $this->dateCreation = $dateCreation;

        return $this;
    }

    public function getAdresse(): ?string
    {
        return $this->adresse;
    }

    public function setAdresse(string $adresse): static
    {
        $this->adresse = $adresse;

        return $this;
    }

    public function getCodePostal(): ?string
    {
        return $this->codePostal;
    }

    public function setCodePostal(string $codePostal): static
    {
        $this->codePostal = $codePostal;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    /**
     * @return Collection<int, Employe>
     */
    public function getEmployes(): Collection
    {
        return $this->employes;
    }

    public function addEmploye(Employe $employe): static
    {
        if (!$this->employes->contains($employe)) {
            $this->employes->add($employe);
            $employe->setEntreprise($this);
        }

        return $this;
    }

    public function removeEmploye(Employe $employe): static
    {
        if ($this->employes->removeElement($employe)) {
            // set the owning side to null (unless already changed)
            if ($employe->getEntreprise() === $this) {
                $employe->setEntreprise(null);
            }
        }

        return $this;
    }

    public function __toString(): string
    {
        return $this->raisonSociale;
    }

    public function getAdresseComplete(): ?string
    {
        return $this->adresse." ".$this->codePostal." ".$this->ville;
    }

    public function getDateCreationFR(): ?string
    {
        return $this->dateCreation->format("d/m/Y");
    }
}

src/Form/EntrepriseType.php
<?php

namespace App\Form;

use App\Entity\Entreprise;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EntrepriseType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('raisonSociale', TextType::class, [
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])

            ->add('dateCreation', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])

            ->add('adresse', TextType::class, [
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])

            ->add('codePostal', TextType::class, [
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])

            ->add('ville', TextType::class, [
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])

            ->add('valider', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Entreprise::class,
        ]);
    }
}

src/Controller/EntrepriseController.php
<?php

namespace App\Controller;

use App\Entity\Entreprise;
use App\Form\EntrepriseType;
use Doctrine\ORM\EntityManager;
use App\Repository\EntrepriseRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\VarDumper\VarDumper;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EntrepriseController extends AbstractController
{
    //----------------------------------------------
    //METHODE INDEX QUI RENVOIE LISTE DES ENTREPRISE
    //----------------------------------------------
    #[Route('/entreprise', name: 'app_entreprise')]
    // public function index(EntityManagerInterface $entityManager): Response
    public function index(EntrepriseRepository $entrepriseRepository): Response
    {
        // $entreprises = $entityManager->getRepository(Entreprise::class)->findAll();
        $entreprises = $entrepriseRepository->findBy([], ["raisonSociale" => "ASC"]);
        // dd($entreprises);
        return $this->render('entreprise/index.html.twig', [
            'entreprises' => $entreprises
        ]);
    }

    //-----------------------------------------------------------------------------------
    //METHODE NEW_EDIT FORM QUI RENVOIE UN FORMULAIRE D'AJOUT / MODIFICATION D'ENTREPRISE
    //-----------------------------------------------------------------------------------
    #[Route('/entreprise/new', name: 'new_entreprise')]
    #[Route('/entreprise/{id}/edit', name: 'edit_entreprise')]
    public function new_edit(Entreprise $entreprise = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        if(!$entreprise){
            $entreprise = new Entreprise();
        }

        $form = $this->createForm(EntrepriseType::class, $entreprise);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            
            $entreprise = $form->getData();
            //equivalent PDO prepare
            $entityManager->persist($entreprise);
            //equivalent PDO execute
            $entityManager->flush();

            return $this->redirectToRoute('app_entreprise');
        }

        return $this->render('entreprise/new.html.twig', [
            'formAddEntreprise' => $form,
            //var edit qui renvoie un booléen permettant l'affichage dynamique du titre du formulaire
            'edit' => $entreprise->getId()
        ]);
    }

    //-----------------------------------------------------
    //METHODE DELETE QUI SUPPRIME UNE ENTREPRISE
    //-----------------------------------------------------
    #[Route('/entreprise/{id}/delete', name: 'delete_entreprise')]
    public function delete(Entreprise $entreprise, EntityManagerInterface $entityManager)
    {
        $entityManager->remove($entreprise);
        $entityManager->flush();

        return $this->redirectToRoute('app_entreprise');
    }

    //-----------------------------------------------------
    //METHODE SHOW QUI RENVOIE LES DETAILS D'UNE ENTREPRISE
    //-----------------------------------------------------
    #[Route('/entreprise/{id}', name: 'show_entreprise')]
    public function show(Entreprise $entreprise): Response
    {
        return $this->render('entreprise/show.html.twig', [
            'entreprise' => $entreprise
        ]);
    }

}

templates/entreprise/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des entreprises{% endblock %}

{% block body %}
    <main class="container mt-5 pt-5">
        <h1 class="display-5 fw-bold text-body-emphasis mb-5">Liste des entreprises :</h1>

        <a class="btn btn-success" href="{{ path('new_entreprise') }}">Ajouter une entreprise</a>
        
        <table class="table">
            <thead>
                <tr>
                    <th>Entreprises</th>
                </tr>
            </thead>
            <tbody>
                {# {{ dump(_context) }} #}
                {% for entreprise in entreprises %}
                    <tr>
                        <td>
                            <a href="{{ path('show_entreprise', {'id': entreprise.id}) }}">{{ entreprise }}</a> 
                            <a href="{{ path('edit_entreprise', {'id': entreprise.id}) }}"><i class="fa-solid fa-pen-to-square"></i></a> |
                            <a class="delbtn" href="{{ path('delete_entreprise', {'id': entreprise.id}) }}"><i class="fa-solid fa-trash"></i></a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
            
        </table class="table">
    </main>

{% endblock %}

templates/entreprise/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formulaire entreprise{% endblock %}

{% block body %}
    <main class="container mt-5 mb-5 pt-5">
        {% if edit %}
            <h1 class="mb-5">Editer l'entreprise :</h1>
        {% else %}
            <h1 class="mb-5">Ajouter une entreprise :</h1>
        {% endif %}
        

        {# {{ form(formAddEntreprise) }} #}
        {{ form_start(formAddEntreprise) }}
            {{ form_row(formAddEntreprise.raisonSociale) }}
            {{ form_row(formAddEntreprise.dateCreation) }}
            {{ form_row(formAddEntreprise.adresse) }}
            <div class="row">
                <div class="col-sm">
                    {{ form_row(formAddEntreprise.codePostal) }}
                </div>
                <div class="col-sm">
                    {{ form_row(formAddEntreprise.ville) }}
                </div>
            </div>
            
        {{ form_end(formAddEntreprise) }}

    </main>
   

{% endblock %}

templates/entreprise/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'une entreprise{% endblock %}

{% block body %}

    <main class="container mt-5 pt-5">
        <h1 class="display-5 fw-bold text-body-emphasis mb-5">Détail de l'entreprise :</h1>
        
        <h2>{{ entreprise }}</h2>
        <p>
            <b>Adresse :</b> {{ entreprise.adresseComplete }} <br>
            <b>Date de création :</b> {{ entreprise.dateCreation | date("d/m/Y") }} <br>
        </p>

        <h3>Liste des salariés :</h3>
        {% if entreprise.employes | length > 0 %}
            <table class="table">
                <thead>
                    <tr>
                        <th>Employé</th>
                    </tr>
                </thead>

                <tbody>
                    {% for employe in entreprise.employes %}
                        <tr>
                            <td><a href="{{ path('show_employe', {'id': employe.id}) }}">{{ employe }}</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
         {% else %}
            <p>Aucun employé dans cette entreprise.</p>
        {% endif %}
    </main>

{% endblock %}