src/Entity/Employe.php
<?php

namespace App\Entity;

use App\Repository\EmployeRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: EmployeRepository::class)]
class Employe
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 50)]
    private ?string $nom = null;

    #[ORM\Column(length: 50)]
    private ?string $prenom = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $dateNaissance = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $dateEmbauche = null;

    #[ORM\ManyToOne(inversedBy: 'employes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Entreprise $entreprise = null;

    #[ORM\Column(length: 50, nullable: true)]
    private ?string $ville = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateNaissance(): ?\DateTimeInterface
    {
        return $this->dateNaissance;
    }

    public function setDateNaissance(?\DateTimeInterface $dateNaissance): static
    {
        $this->dateNaissance = $dateNaissance;

        return $this;
    }

    public function getDateEmbauche(): ?\DateTimeInterface
    {
        return $this->dateEmbauche;
    }

    public function setDateEmbauche(\DateTimeInterface $dateEmbauche): static
    {
        $this->dateEmbauche = $dateEmbauche;

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): static
    {
        $this->entreprise = $entreprise;

        return $this;
    }

    public function getVille(): ?string
    {
        return $this->ville;
    }

    public function setVille(?string $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function __toString()
    {
        return $this->prenom." ".$this->nom;
    }

    public function getAge(): ?string
    {
        $now = new \DateTime();
        $interval = $this->dateNaissance->diff($now);
        return $interval->format("%Y");
    }

}

src/Form/EmployeType.php
<?php

namespace App\Form;

use App\Entity\Employe;
use App\Entity\Entreprise;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EmployeType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom', TextType::class, [
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])

            ->add('prenom', TextType::class, [
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])

            ->add('dateNaissance', DateType::class, [
                'widget' => 'single_text',
                'required' => false,
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])

            ->add('dateEmbauche', DateType::class, [
                'widget' => 'single_text',
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])

            ->add('ville', TextType::class, [
                'required' => false,
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])

            ->add('entreprise', EntityType::class, [
                'class' => Entreprise::class,
                //'choice_label' => 'raisonSociale',
                'attr' => [
                    'class' => 'form-control mb-3'
                ]
            ])

            ->add('valider', SubmitType::class, [
                'attr' => [
                    'class' => 'btn btn-success'
                ]
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Employe::class,
        ]);
    }
}

src/Controller/EmployeController.php
<?php

namespace App\Controller;

use App\Entity\Employe;
use App\Form\EmployeType;
use App\Repository\EmployeRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

class EmployeController extends AbstractController
{
    //-----------------------------------------------
    //METHODE INDEX QUI RENVOIE LA LISTE DES EMPLOYES
    //-----------------------------------------------
    #[Route('/employe', name: 'app_employe')]
    public function index(EmployeRepository $employeRepository): Response
    {
        $employes = $employeRepository->findBy([], ["nom" => "ASC"]);
        return $this->render('employe/index.html.twig', [
            'employes' => $employes
        ]);
    }

    //------------------------------------------------------------
    //METHODE NEW FORM QUI RENVOIE UN FORMULAIRE D'AJOUT D'EMPLOYE
    //------------------------------------------------------------
    #[Route('/employe/new', name: 'new_employe')]
    #[Route('/employe/{id}/edit', name: 'edit_employe')]
    public function new_edit(Employe $employe = null, Request $request, EntityManagerInterface $entityManager): Response
    {
        if(!$employe){
            $employe = new Employe();
        }

        $form = $this->createForm(EmployeType::class, $employe);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            
            $employe = $form->getData();
            $entityManager->persist($employe);
            $entityManager->flush();

            return $this->redirectToRoute('app_employe');
        }

        return $this->render('employe/new.html.twig', [
            'formAddEmploye' => $form,
            'edit' => $employe->getId()
        ]);
    }

    //--------------------------------------
    //METHODE DELETE QUI SUPPRIME UN EMPLOYE
    //--------------------------------------
    #[Route('/employe/{id}/delete', name: 'delete_employe')]
    public function delete(Employe $employe, EntityManagerInterface $entityManager)
    {
        $entityManager->remove($employe);
        $entityManager->flush();

        return $this->redirectToRoute('app_employe');
    }

    //-------------------------------------------------
    //METHODE SHOW QUI RENVOIE LES DETAILS D'UN EMPLOYE
    //-------------------------------------------------
    #[Route('/employe/{id}', name: 'show_employe')]
    public function show(Employe $employe): Response
    {
        return $this->render('employe/show.html.twig', [
            'employe' => $employe
        ]);
    }
}

templates/employe/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des employés{% endblock %}

{% block body %}

    <main class="container mt-5 pt-5">
        <h1 class="display-5 fw-bold text-body-emphasis mb-5">Liste des employés</h1>

        <a class="btn btn-success" href="{{ path('new_employe') }}">Ajouter un employé</a>
            
        <table class="table">
            <thead>
                <tr>
                    <th>Employés</th>
                </tr>
            </thead>
            <tbody>
                {% for employe in employes %}
                <tr>
                    <td>
                        <a href="{{ path('show_employe', {'id': employe.id}) }}">{{ employe }}</a>  
                        (<a href="{{ path('show_entreprise', {'id': employe.entreprise.id}) }}">{{ employe.entreprise.raisonSociale }}</a>) 
                        <a href="{{ path('edit_employe', {'id': employe.id}) }}"><i class="fa-solid fa-pen-to-square"></i></a> |
                        <a class="delbtn" href="{{ path('delete_employe', {'id': employe.id}) }}"><i class="fa-solid fa-trash"></i></a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </main>

{% endblock %}

templates/employe/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formulaire employé{% endblock %}

{% block body %}
    <main class="container mt-5 mb-5 pt-5">
        {% if edit %}
            <h1 class="mb-5">Editer l'employé :</h1>
        {% else %}
            <h1 class="mb-5">Ajouter un employé :</h1>
        {% endif %}
        

        {# {{ form(formAddEmploye) }} #}

        {{ form_start(formAddEmploye) }}
            <div class="row">
                <div class="col-sm">
                    {{ form_row(formAddEmploye.nom) }}
                </div>
                <div class="col-sm">
                    {{ form_row(formAddEmploye.prenom) }}
                </div>
            </div>
           {{ form_row(formAddEmploye.dateNaissance) }}
           {{ form_row(formAddEmploye.ville) }}
           {{ form_row(formAddEmploye.dateEmbauche) }}
           {{ form_row(formAddEmploye.entreprise) }}
           {{ form_row(formAddEmploye.valider) }}
        {{ form_end(formAddEmploye) }}
        
    </main>
   

{% endblock %}

templates/employe/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Détail d'un employé{% endblock %}

{% block body %}
    
    <main class="container mt-5 pt-5">
        <h1 class="display-5 fw-bold text-body-emphasis mb-5">Détail de l'employé :</h1>
        
        <h2>{{ employe }}</h2>
        <p>
            <b>Employeur :</b> <a href="{{ path('show_entreprise', {'id': employe.entreprise.id}) }}">{{ employe.entreprise }}</a> <br>
            
            <b>Date d'embauche :</b> {{ employe.dateEmbauche | date("d/m/Y") }} <br>
            
            <b>Ville de résidence :</b> 
            {% if employe.ville | length > 0 %}
                {{ employe.ville }} <br>
            {% else %}
                Information non renseignée. <br>
            {% endif %}

            <b>Date de naissance :</b> 
            {% if employe.dateNaissance | length > 0 %}
                {{ employe.dateNaissance | date("d/m/Y") }} <br>
            {% else %}
                Information non renseignée. <br>
            {% endif %}
            
            <b>Age :</b> 
            {% if employe.dateNaissance | length > 0 %}
                {{ employe.age }} ans. <br>
            {% else %}
                Information non renseignée. <br>
            {% endif %}
            
        </p>
    </main>

{% endblock %}